CREATE TABLE DWH.DWH_LOG (
  LOG_ID        NUMBER NOT NULL,
  PIPELINE      VARCHAR2(100),
  START_TS      TIMESTAMP,
  END_TS        TIMESTAMP,
  STATUS        VARCHAR2(20),
  ROWS_READ     NUMBER,
  ROWS_WRITTEN  NUMBER,
  ERROR_MSG     VARCHAR2(4000),

  CONSTRAINT PK_DWH_LOG PRIMARY KEY (LOG_ID)
);

CREATE SEQUENCE DWH.LOG_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE;


CREATE SEQUENCE DWH.DIM_COMPETITION_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE TABLE DWH.DIM_COMPETITION (
  COMPETITION_ID    NUMBER DEFAULT DWH.DIM_COMPETITION_SEQ.NEXTVAL NOT NULL,
  CODE       VARCHAR2(100) NOT NULL,
  LABEl      VARCHAR2(100) NOT NULL,
  URL        VARCHAR2(255),
  LOG_ID     NUMBER,
  CREATE_TS  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATE_TS  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  DELETE_TS  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

  CONSTRAINT PK_COMPETITION PRIMARY KEY (COMPETITION_ID),
  
  CONSTRAINT FK_LOG_COMPETITION FOREIGN KEY (LOG_ID)
    REFERENCES DWH.DWH_LOG(LOG_ID)
);

CREATE SEQUENCE DWH.DIM_COACH_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE TABLE DWH.DIM_COACH (
  COACH_ID      NUMBER DEFAULT DWH.DIM_COACH_SEQ.NEXTVAL NOT NULL,
  COACH_NAME    VARCHAR2(100) NOT NULL,
  LOG_ID        NUMBER,
  CREATE_TS     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATE_TS     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  DELETE_TS  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

  CONSTRAINT PK_COACH PRIMARY KEY (COACH_ID),
  
  CONSTRAINT FK_LOG_COACH FOREIGN KEY (LOG_ID)
    REFERENCES DWH.DWH_LOG(LOG_ID)
);


CREATE SEQUENCE DWH.DIM_TEAM_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE TABLE DWH.DIM_TEAM (
  TEAM_ID         NUMBER DEFAULT DWH.DIM_TEAM_SEQ.NEXTVAL NOT NULL,
  TEAM_NAME       VARCHAR2(100) NOT NULL,
  LOG_ID          NUMBER,
  CREATE_TS       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATE_TS       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  DELETE_TS  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

  CONSTRAINT PK_TEAM PRIMARY KEY (TEAM_ID),
  CONSTRAINT FK_LOG_TEAM FOREIGN KEY (LOG_ID)
  REFERENCES DWH.DWH_LOG(LOG_ID),
);


CREATE SEQUENCE DWH.DIM_LOCATION_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE TABLE DWH.DIM_LOCATION (
  LOCATION_ID    NUMBER DEFAULT DWH.DIM_LOCATION_SEQ.NEXTVAL NOT NULL,
  LOCATION       VARCHAR2(100) NOT NULL,
  LOG_ID          NUMBER,
  CREATE_TS       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATE_TS       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  DELETE_TS  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

  CONSTRAINT PK_TEAM PRIMARY KEY (TEAM_ID),
  CONSTRAINT FK_LOG_TEAM FOREIGN KEY (LOG_ID)
  REFERENCES DWH.DWH_LOG(LOG_ID),
);

