CREATE TABLE ODS.ODS_LOG (
  LOG_ID        NUMBER NOT NULL,
  PIPELINE      VARCHAR2(100),
  START_TS      TIMESTAMP,
  END_TS        TIMESTAMP,
  STATUS        VARCHAR2(20),
  ROWS_READ     NUMBER,
  ROWS_WRITTEN  NUMBER,
  ERROR_MSG     VARCHAR2(4000),

  CONSTRAINT PK_ODS_LOG PRIMARY KEY (LOG_ID)
);

CREATE SEQUENCE ODS.LOG_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE;


CREATE SEQUENCE ODS.COMPETITION_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE TABLE ODS.COMPETITION (
  COMPETITION_ID    NUMBER DEFAULT ODS.COMPETITION_SEQ.NEXTVAL NOT NULL,
  CODE       VARCHAR2(100) NOT NULL,
  LABEl      VARCHAR2(100) NOT NULL,
  URL        VARCHAR2(255),
  LOG_ID     NUMBER,
  CREATE_TS  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATE_TS  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

  CONSTRAINT PK_COMPETITION PRIMARY KEY (COMPETITION_ID),
  CONSTRAINT UQ_COMPETITION_CODE UNIQUE (CODE),
  CONSTRAINT UQ_COMPETITION_LABEL UNIQUE (LABEL),
  
  CONSTRAINT FK_LOG_COMPETITION FOREIGN KEY (LOG_ID)
    REFERENCES ODS.ODS_LOG(LOG_ID)
);

CREATE SEQUENCE ODS.COACH_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE TABLE ODS.COACH (
  COACH_ID     NUMBER DEFAULT ODS.COACH_SEQ.NEXTVAL NOT NULL,
  COACH_NAME   VARCHAR2(100) NOT NULL,
  LOG_ID       NUMBER,
  CREATE_TS    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATE_TS    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

  CONSTRAINT PK_COACH PRIMARY KEY (COACH_ID),
  CONSTRAINT UQ_COACH_NAME UNIQUE (COACH_NAME),
  
  CONSTRAINT FK_LOG_COACH FOREIGN KEY (LOG_ID)
    REFERENCES ODS.ODS_LOG(LOG_ID)
);


CREATE SEQUENCE ODS.TEAM_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE TABLE ODS.TEAM (
  TEAM_ID         NUMBER DEFAULT ODS.TEAM_SEQ.NEXTVAL NOT NULL,
  TEAM_NAME       VARCHAR2(100) NOT NULL,
  COACH_ID        NUMBER,
  COMPETITION_ID  NUMBER,
  LOG_ID          NUMBER,
  CREATE_TS       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATE_TS       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

  CONSTRAINT PK_TEAM PRIMARY KEY (TEAM_ID),
  CONSTRAINT FK_LOG_TEAM FOREIGN KEY (LOG_ID)
  REFERENCES ODS.ODS_LOG(LOG_ID),
  CONSTRAINT FK_TEAM_COACH FOREIGN KEY (COACH_ID)
    REFERENCES ODS.COACH(COACH_ID),
  CONSTRAINT FK_TEAM_COMPETITION FOREIGN KEY (COMPETITION_ID)
    REFERENCES ODS.COMPETITION(COMPETITION_ID)
);


CREATE SEQUENCE ODS.GAME_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE;
  
CREATE TABLE ODS.GAME (
	GAME_ID   NUMBER DEFAULT ODS.GAME_SEQ.NEXTVAL NOT NULL,
	COMPETITION_ID  NUMBER,
	TEAM_HOME_ID    NUMBER,
	TEAM_AWAY_ID    NUMBER,
	TD_HOME         NUMBER,
	TD_AWAY         NUMBER,
	GAME_DATE       TIMESTAMP,
	GAME_LABEL      VARCHAR2(100),
	LOG_ID          NUMBER,
    CREATE_TS       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_TS       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	
  CONSTRAINT PK_GAME PRIMARY KEY (GAME_ID),
	
  CONSTRAINT FK_GAME_COMPETITION FOREIGN KEY (COMPETITION_ID)
    REFERENCES ODS.COMPETITION(COMPETITION_ID),
	
  CONSTRAINT FK_GAME_TEAM_HOME FOREIGN KEY (TEAM_HOME_ID)
    REFERENCES ODS.TEAM(TEAM_ID),
	
  CONSTRAINT FK_GAME_TEAM_AWAY FOREIGN KEY (TEAM_AWAY_ID)
    REFERENCES ODS.TEAM(TEAM_ID),

  CONSTRAINT FK_LOG_GAME FOREIGN KEY (LOG_ID)
    REFERENCES ODS.ODS_LOG(LOG_ID)
);

